### ISSUE TITLE
xxh-screen: screen is terminating

### ISSUE THREAD

**Issue by c1au6i0** [xxh/xxh-plugin-prerun-sudo#1]
Hello,
I have installed and launched the plugin with:
```
xxh +I xxh-plugin-prerun-cor
xxh myhost +if
xxh-screen -S pippo
```
And I got the following error:
```
[screen is terminating]
```
Same if I just use just `xxh-screen`.

Argument `ls` is not recognized:
```
>  xxh-screen -l
Bad session name 'home/myName/.xxh/.xxh/shells/xxh-shell-/build/entrypoint.sh'
```
...and folder `/home/myName/.xxh/.xxh/shells/xxh-shell-/` does not exist.

I am missing something about the use of the command?

Thank you guys!
C1au6i0 :)

**Comment by anki-code** [comment]
Hi! 
xxh-screen run this in fact:

https://github.com/xxh/xxh-plugin-prerun-core/blob/96c9aa20cb3e14b5ea16d1f3b14df470e0e7c404/xxh-screen#L1-L3

The error:

> Bad session name 'home/myName/.xxh/.xxh/shells/xxh-shell-/build/entrypoint.sh'

Looks like that `$XXH_SHELL` is empty and this is the cause of error. 

I've updated the xxh-shell-zsh and xxh-shell-fish shells. Please update the xxh shell you use.

```python
xxh +RI xxh-shell-zsh
# or
xxh +RI xxh-shell-fish
# and
xxh myhost +if
xxh-screen
```

**Comment by c1au6i0** [comment]
Great, thank you so much @anki-code !

Now creating a session works as a charm. 
With `xxh-screen -ls` I still experience the error:

```
Bad session name 'home/myName/.xxh/.xxh/shells/xxh-shell-zsh/build/entrypoint.sh'
```
not sure why.
```
> echo $XXH_HOME
/home/myName/.xxh
```

and the file
`home/myName/.xxh/.xxh/shells/xxh-shell-zsh/build/entrypoint.sh` is there.

Best

**Comment by anki-code** [comment]
After you start `xxh-screen` you can use `screen -ls` ordinarly.

The `xxh-screen` command is just used to start the new screen.

**Comment by c1au6i0** [comment]
Great, thank you so much @anki-code!
